name: Frontend Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ✅ Checkout Code
        uses: actions/checkout@v3

      - name: ✅ Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: ✅ Install Dependencies
        run: npm install

      - name: ✅ Build React App
        run: npm run build

      - name: ✅ Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

          - name: ✅ Reload Nginx
        run: |
          ssh -o StrictHostKeyChecking=no simran@122.160.115.189 "sudo systemctl restart nginx"


            - name: ✅ Reload Nginx
        run: |
          ssh -o StrictHostKeyChecking=no simran@122.160.115.189 "sudo systemctl reload nginx"
          sleep 2
          ssh -o StrictHostKeyChecking=no simran@122.160.115.189 "sudo systemctl restart nginx"
