name: Frontend Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: ✅ Checkout Code
        uses: actions/checkout@v3

      - name: ✅ Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: ✅ Install Dependencies
        run: npm install

      - name: ✅ Build React App
        run: npm run build

      # ✅ Upload build folder using appleboy/ssh-action
      - name: ✅ Upload Files To Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: "122.160.115.189"   # ✅ No mistake here
          username: "simran"
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "build/*"
          target: "/var/www/frontend/"

      - name: ✅ Restart Nginx
        uses: appleboy/ssh-action@v1.0.2
        with:
          host: "122.160.115.189"
          username: "simran"
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo systemctl restart nginx
